### ISSUE TITLE
API/Connection event subscription mechansim

### ISSUE THREAD

**Issue by stze** [splone/splonebox-core#60]
As discussed with @bontric we need to introduce an event subscription mechansim. Therefore we need to implement:
- connection event subscripe/unsubscripe function
- connection event broadcast function

Event types are represented as strings and stored in a global hashmap. If a connection subscribes to an event, the event string is saved in a connection event hashmap. In the broadcast function, for every connection we check if it has subscribed to the event, therefore we use the connection event hashmap. Then we send the packet to all connections which subscribed to the event. During the unsubscribe function, the event is removed from the connection event hashmap.

Subscribe/Unsubscribe can be triggered by new API calls _subscribe_ and _unsubscribe_.
### Subscribe API call

```
[0, msgid, "subscribe", ["EventName"]]
```
### Unsubscribe API call

```
[0, msgid, "unsubscribe", ["EventName"]]
```
### Notify

A msgpack-rpc _notification message_ is used for the notify mechanism. The notification message is a msgpack-rpc with method `method` and argument `args`. This will have the same effect as a request, but no response will be recieved.

```
[2, "EventName", args]
```

**Comment by bontric** [comment]
Do publishers need to register an event before someone can subscribe to it? 
I recall we talked about that, but I think it's probably unnecessary. 

If a plugin doesn't need to register itself as publisher, the handling seems quite simple. Also multiple publishers for a single event don't have to be handled in any special way. 

I currently can't see how registering a publisher would be better, but we might want to consider that

**Comment by bontric** [comment]
Are we going to drop the result request in favor for the publish-subscribe model? Or do we keep both? 
(It's hard to drop the result just after we released it.. But I think it would remove some complexity and make the overall handling nicer)

**Comment by mkind** [comment]
> I currently can't see how registering a publisher would be better, but we might want to consider that

Some details are still missing for my understanding. For instance, who is managing the events? Consider the case that I want to subscribe for a result of a specific plugin. How is this done? What is the event name? Are they unique and global or is every publisher able to provide custom events?

**Comment by stze** [comment]
The flow is quite easy.

> who is managing the events?

The core.

> Consider the case that I want to subscribe for a result of a specific plugin. How is this done?

_Plugin A_ sends a subscription Call to the Core and registers for the event "foobar". The _core_ checks if the event is already present or creates a new one.

_Plugin B_ sends a _notify_ message to the core with the event "foobar". The message is now broadcasted to all plugins which subscribed for "foobar", including _Plugin A_. 

> What is the event name? is every publisher able to provide custom events?

Since every plugin is able to provide custom events, the event name can be chosen freely.

**Comment by mkind** [comment]
Ok, thanks for the details. This was the missing link :)

**Comment by stze** [comment]
@bontric 

> Are we going to drop the result request in favor for the publish-subscribe model? Or do we keep both? 

At first, i think we keep both and check later again if we really want to drop the result API call.

**Comment by stze** [comment]
@mkind @bontric the notfiy/event flow needs to be adapted, otherwise we would overload the msgpack-rpc notify functionality:

A _notification_ msgpack-rpc message is an equivalent to _request_ msgpack-rpc message, but without requiring a response. So we can use the function for task's where we do not need a response, like "Plugin A notifies the core with data to save in a database", or "Core notifies Plugin B to redraw the GUI". The cool thing is, we can use every dispatcher function also as dispatcher for notifcations, the only difference is that no response is sent. With this, we are msgpack-rpc protocol conform. 

For the purpose of broadcasting data, e.g. results, to more than one plugin, we need a new API call (broadcast) which has the following properties:
- method name = _broadcast_
- args = _["EventName", [args]]_
1. _Plugin A_ subscribes for event "foobar"
2. _Plugin B_ subscribes for event "foobar"
3. _Plugin C_ sends "broadcast" request/notifcation to _core_
   - `[0, 1234, "broadcast", ["foobar", ["Hello World"]]`
   - or `[2, "broadcast", ["foobar", ["Hello World"]]`
4. Core sends event _foobar_ with args to _Plugin A_ and _Plugin B_
   - `[2, "foobar", ["Hello World"]`

**Comment by mkind** [comment]
> So we can use the function for task's where we do not need a response

It might be a problem, that as soon as notifications are used to explicitly trigger executions (e.g. redrawing something, saving data), "notifications" compete with the traditional "run" call. So there should be a clear reason (and maybe a clear definition) when to use notifications and when to use them not.

> For the purpose of broadcasting data, e.g. results, to more than one plugin

What is the use case for broadcasts? IMHO, broadcasts are obsolete. If a plugin is interested in a specific kind of information or notification it subscribes to it. An event might be named "broadcast", however this is a very unprecise event name and it does not make any sense to me to have such an event.

**Comment by stze** [comment]
> It might be a problem, that as soon as notifications are used to explicitly trigger executions (e.g. redrawing something, saving data), "notifications" compete with the traditional "run" call. So there should be a clear reason (and maybe a clear definition) when to use notifications and when to use them not.

notification is not an API call. notification is a msgpack rpc protocol message type, like request. It does not really compete with the run call. but you are right, we should definitely think about, when to use notifications or request for specific API calls, like run. 

> What is the use case for broadcasts? IMHO, broadcasts are obsolete. If a plugin is interested in a specific kind of information or notification it subscribes to it. An event might be named "broadcast", however this is a very unprecise event name and it does not make any sense to me to have such an event.

i don't understand. without a `broadcast` call, how do plugin's send event's to event subscriber's? otherwise only the core would be able to send event's to event subscribers. the name broadcast is maybe not optimal. do you have an idea what name is more appropriate?

**Comment by mkind** [comment]
> otherwise only the core would be able to send event's to event subscribers.

Ok, you mean, it's a multicast sent by the core to all subscribers?

**Comment by stze** [comment]
> Ok, you mean, it's a multicast sent by the core to all subscribers?

i think the term broadcast is more precise, because we send events to all event subscribers.

**Comment by mkind** [comment]
introduced in [version 0.1.7](https://github.com/splone/splonebox-core/releases/tag/v0.1.7)
